version: "3"

services:

  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    image: nutanixdev/flask_app
    tty: true
    ports:
      - 5001:5001
    network_mode: "host"

